version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,HOST_PLAINTEXT:PLAINTEXT,HOST_PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092,HOST_PLAINTEXT://localhost:9093,HOST_PLAINTEXT_INTERNAL://localhost:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  
  data_generator_train:
    container_name: data_generator_train
    depends_on:
      - broker
    build:
      context: ./data_generators/mixing
    environment:
      - CONFIG=experiment.json
      - PIPELINE_TYPE=train
      - SOURCE_TYPE=s3
      - SOURCE_NAME=stream-gait-data-disser
      - DEST_TYPE=file
      - DEST_NAME=data.txt
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials

  data_generator_test:
    container_name: data_generator_test
    depends_on:
      - broker
    build:
      context: ./data_generators/mixing
    environment:
      - CONFIG=experiment.json
      - PIPELINE_TYPE=test
      - SOURCE_TYPE=s3
      - SOURCE_NAME=stream-gait-data-disser
      - DEST_TYPE=file
      - DEST_NAME=data.txt
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials

  # simple_processor:
  #   image: simple_processor:latest
  #   depends_on:
  #     - broker
  #     - data_generator